/**
 * WAI-ARIA 1.2 role definitions.
 * Descriptions are taken verbatim from the W3C WAI-ARIA 1.2 specification:
 * https://www.w3.org/TR/wai-aria-1.2/
 *
 * primaryCategory — determines which section heading a role appears under
 *                   in the grouped "All" view.
 * categories      — all categories this role belongs to; used for filtering.
 * usage.element   — implicit HTML element, or how to apply
 * usage.avoid     — when NOT to use this role
 * usage.required  — required companion attributes
 * usage.nestedIn  — roles this must be nested within
 */

export const CATEGORIES = [
  { id: 'all',        label: 'All' },
  { id: 'landmark',   label: 'Landmark' },
  { id: 'widget',     label: 'Widget' },
  { id: 'document',   label: 'Document structure' },
  { id: 'live-region',label: 'Live region' },
  { id: 'window',     label: 'Window' },
]

export const CATEGORY_LABELS = {
  landmark:    'Landmark roles',
  widget:      'Widget roles',
  document:    'Document structure roles',
  'live-region': 'Live region roles',
  window:      'Window roles',
}

// Grouped view renders in this order
export const SECTION_ORDER = ['landmark', 'widget', 'document', 'window']

export const ROLES = [

  // ── LANDMARK ROLES ────────────────────────────────────────────
  {
    id: 'banner',
    name: 'banner',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A region that contains mostly site-oriented content, rather than page-specific content.',
    usage: {
      element: 'Implicit on <header> when a direct child of <body>.',
      avoid: 'Do not use on <header> elements nested inside <article>, <section>, or other sectioning content.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'complementary',
    name: 'complementary',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A supporting section of the document, designed to be complementary to the main content at a similar level in the DOM hierarchy, but remains meaningful when separated from the main content.',
    usage: {
      element: 'Implicit on <aside>.',
      avoid: null,
      required: 'If multiple complementary landmarks exist, label each with aria-label or aria-labelledby.',
      nestedIn: null,
    },
  },
  {
    id: 'contentinfo',
    name: 'contentinfo',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A large perceivable region that contains information about the parent document.',
    usage: {
      element: 'Implicit on <footer> when a direct child of <body>.',
      avoid: 'Do not use on <footer> elements nested inside <article>, <section>, or other sectioning content.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'form',
    name: 'form',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A landmark region that contains a collection of items and objects that, as a whole, combine to create a form. See related search.',
    usage: {
      element: 'Implicit on <form> only when it has an accessible name via aria-label or aria-labelledby.',
      avoid: 'Without an accessible name, <form> is not exposed as a landmark.',
      required: 'aria-label or aria-labelledby to be recognised as a landmark.',
      nestedIn: null,
    },
  },
  {
    id: 'main',
    name: 'main',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'The main content of a document.',
    usage: {
      element: 'Implicit on <main>.',
      avoid: 'One per page only. Add id="main-content" as a skip link target.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'navigation',
    name: 'navigation',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A collection of navigational elements (usually links) for navigating the document or related documents.',
    usage: {
      element: 'Implicit on <nav>.',
      avoid: null,
      required: 'If multiple navigation landmarks exist, label each distinctly with aria-label or aria-labelledby.',
      nestedIn: null,
    },
  },
  {
    id: 'region',
    name: 'region',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A perceivable section containing content that is relevant to a specific, author-specified purpose and sufficiently important that users will likely want to be able to navigate to the section easily and to have it listed in a summary of the page. Such a page summary could be generated dynamically by a user agent or assistive technology.',
    usage: {
      element: 'Implicit on <section> only when it has an accessible name.',
      avoid: 'Without an accessible name, <section> is not exposed as a landmark region.',
      required: 'aria-label or aria-labelledby — required for landmark exposure.',
      nestedIn: null,
    },
  },
  {
    id: 'search',
    name: 'search',
    primaryCategory: 'landmark',
    categories: ['landmark'],
    description: 'A landmark region that contains a collection of items and objects that, as a whole, combine to create a search facility. See related form.',
    usage: {
      element: 'No implicit HTML equivalent in ARIA 1.2. Apply to a <form> or wrapper element containing search controls. The HTML <search> element (2024) implies this role.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },

  // ── WIDGET ROLES ──────────────────────────────────────────────
  {
    id: 'alert',
    name: 'alert',
    primaryCategory: 'widget',
    categories: ['widget', 'live-region'],
    description: 'A type of live region with important, and usually time-sensitive, information. See related alertdialog and status.',
    usage: {
      element: 'No HTML equivalent. Apply to any container element.',
      avoid: 'Do not move focus into the alert — it announces without moving focus. Use role="alertdialog" when focus is needed.',
      required: 'Render the container in the DOM before injecting content — do not dynamically create and fill simultaneously.',
      nestedIn: null,
    },
  },
  {
    id: 'button',
    name: 'button',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An input that allows for user-triggered actions when clicked or pressed. See related link.',
    usage: {
      element: 'Implicit on <button>. Use native <button> wherever possible.',
      avoid: null,
      required: 'If applied to a non-button element: tabindex="0" and handle Enter and Space keydown events.',
      nestedIn: null,
    },
  },
  {
    id: 'checkbox',
    name: 'checkbox',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A checkable input that has three possible values: true, false, or mixed. See related button and option.',
    usage: {
      element: 'Implicit on <input type="checkbox">. Use native checkbox wherever possible.',
      avoid: null,
      required: 'aria-checked="true|false|mixed". Custom implementation: tabindex="0", handle Space key.',
      nestedIn: null,
    },
  },
  {
    id: 'combobox',
    name: 'combobox',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An input that controls another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of the input.',
    usage: {
      element: 'Applied to the text input element that controls the popup.',
      avoid: null,
      required: 'aria-expanded, aria-haspopup, aria-controls (pointing to the popup listbox or grid).',
      nestedIn: null,
    },
  },
  {
    id: 'gridcell',
    name: 'gridcell',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A cell in a grid or treegrid.',
    usage: {
      element: 'Implicit on <td> within a grid. Use for interactive cells in a grid widget.',
      avoid: null,
      required: null,
      nestedIn: 'row, which must be within grid or treegrid.',
    },
  },
  {
    id: 'link',
    name: 'link',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An interactive reference to an internal or external resource that, when activated, causes the user agent to navigate to that resource. See related button.',
    usage: {
      element: 'Implicit on <a href>. Use native <a> wherever possible.',
      avoid: 'Do not apply to non-anchor elements — they receive no keyboard support by default.',
      required: 'Must have an accessible name. If on a non-anchor: tabindex="0" and handle Enter key.',
      nestedIn: null,
    },
  },
  {
    id: 'listbox',
    name: 'listbox',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A widget that allows the user to select one or more items from a list of choices. See related combobox and list.',
    usage: {
      element: 'Analogous to a styled <select>. Applied to the container of option elements.',
      avoid: null,
      required: 'aria-label or aria-labelledby. Children must have role="option" with aria-selected.',
      nestedIn: null,
    },
  },
  {
    id: 'log',
    name: 'log',
    primaryCategory: 'widget',
    categories: ['widget', 'live-region'],
    description: 'A type of live region where new information is added in meaningful order and old information may disappear. See related marquee.',
    usage: {
      element: 'No HTML equivalent. Apply to a container like <div> or <section>.',
      avoid: null,
      required: 'Announces politely by default. Add aria-live="polite" explicitly for wider support.',
      nestedIn: null,
    },
  },
  {
    id: 'marquee',
    name: 'marquee',
    primaryCategory: 'widget',
    categories: ['widget', 'live-region'],
    description: 'A type of live region where non-essential information changes frequently. See related log.',
    usage: {
      element: 'Applied to a container for frequently updating, non-essential content.',
      avoid: 'Auto-updating content creates significant barriers. Provide pause controls and respect prefers-reduced-motion.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'menuitem',
    name: 'menuitem',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An option in a set of choices contained by a menu or menubar. See related menuitemcheckbox and menuitemradio.',
    usage: {
      element: 'No HTML equivalent. Apply to items within a menu widget.',
      avoid: 'Do not use for site navigation — use <nav> with links. Menu roles are for application-style action menus.',
      required: null,
      nestedIn: 'menu or menubar.',
    },
  },
  {
    id: 'menuitemcheckbox',
    name: 'menuitemcheckbox',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A menuitem with a checkable state whose possible values are true, false, or mixed. See related menuitem and menuitemradio.',
    usage: {
      element: 'No HTML equivalent.',
      avoid: null,
      required: 'aria-checked="true|false|mixed".',
      nestedIn: 'menu or menubar.',
    },
  },
  {
    id: 'menuitemradio',
    name: 'menuitemradio',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A checkable menuitem in a set of elements with the same role, only one of which can be checked at a time. See related menuitem and menuitemcheckbox.',
    usage: {
      element: 'No HTML equivalent.',
      avoid: null,
      required: 'aria-checked="true|false".',
      nestedIn: 'menu or menubar.',
    },
  },
  {
    id: 'meter',
    name: 'meter',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An element that represents a scalar measurement within a known range, or a fractional value. See related progressbar.',
    usage: {
      element: 'Implicit on <meter>. Use native <meter> wherever possible.',
      avoid: 'Use progressbar for task progress; meter is for static measurements such as disk usage or battery level.',
      required: 'aria-valuenow, aria-valuemin, aria-valuemax. aria-valuetext for a human-readable value.',
      nestedIn: null,
    },
  },
  {
    id: 'option',
    name: 'option',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A selectable item in a select list. See related listbox.',
    usage: {
      element: 'Analogous to <option> within <select>.',
      avoid: null,
      required: 'aria-selected="true|false".',
      nestedIn: 'listbox or a combobox popup.',
    },
  },
  {
    id: 'progressbar',
    name: 'progressbar',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An element that displays the progress status for tasks that take a long time. See related meter and status.',
    usage: {
      element: 'Implicit on <progress>. Use native <progress> wherever possible.',
      avoid: null,
      required: 'aria-valuenow, aria-valuemin (0), aria-valuemax (100) for determinate. Omit aria-valuenow for indeterminate.',
      nestedIn: null,
    },
  },
  {
    id: 'radio',
    name: 'radio',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A checkable input in a group of elements with the same role, only one of which can be checked at a time. See related radiogroup and checkbox.',
    usage: {
      element: 'Implicit on <input type="radio">. Use native radio inputs wherever possible.',
      avoid: null,
      required: 'aria-checked="true|false". Must be within a radiogroup.',
      nestedIn: 'radiogroup.',
    },
  },
  {
    id: 'scrollbar',
    name: 'scrollbar',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A graphical object that controls the scrolling of content within a viewing area, regardless of whether the content is fully displayed within the viewing area.',
    usage: {
      element: 'No HTML equivalent. Apply to a custom scrollbar element.',
      avoid: 'Use native scrollbars wherever possible — they have full browser and OS accessibility support.',
      required: 'aria-controls (the scrollable region), aria-valuenow, aria-valuemin, aria-valuemax, aria-orientation.',
      nestedIn: null,
    },
  },
  {
    id: 'searchbox',
    name: 'searchbox',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A type of textbox intended for specifying search criteria. See related textbox.',
    usage: {
      element: 'Implicit on <input type="search">. Apply to a text input used specifically for search.',
      avoid: null,
      required: 'Accessible name via aria-label or associated <label>. Use within a role="search" landmark.',
      nestedIn: null,
    },
  },
  {
    id: 'slider',
    name: 'slider',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A user input where the user selects a value from within a given range.',
    usage: {
      element: 'Analogous to <input type="range">. Use native range input wherever possible.',
      avoid: null,
      required: 'aria-valuenow, aria-valuemin, aria-valuemax. Handle arrow keys, Home, and End.',
      nestedIn: null,
    },
  },
  {
    id: 'spinbutton',
    name: 'spinbutton',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A form of range that expects the user to select from among discrete choices.',
    usage: {
      element: 'Analogous to <input type="number">.',
      avoid: null,
      required: 'aria-valuenow, aria-valuemin, aria-valuemax. Handle up/down arrow keys, Home, End, Page Up/Down.',
      nestedIn: null,
    },
  },
  {
    id: 'status',
    name: 'status',
    primaryCategory: 'widget',
    categories: ['widget', 'live-region'],
    description: 'A type of live region whose content is advisory information for the user but is not important enough to justify an alert, often but not necessarily presented as a status bar. See related alert and progressbar.',
    usage: {
      element: 'No HTML equivalent. Apply to any container element.',
      avoid: null,
      required: 'Render in the DOM before injecting content. Announces politely — equivalent to aria-live="polite".',
      nestedIn: null,
    },
  },
  {
    id: 'switch',
    name: 'switch',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A type of checkbox that represents on/off values, as opposed to checked/unchecked values.',
    usage: {
      element: 'No HTML equivalent. Apply to a <button> or custom toggle element.',
      avoid: 'Do not use for checkboxes in forms — use role="checkbox" for true/false form inputs.',
      required: 'aria-checked="true|false". Accessible name describing what is toggled.',
      nestedIn: null,
    },
  },
  {
    id: 'tab',
    name: 'tab',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user.',
    usage: {
      element: 'No HTML equivalent. Applied to the tab trigger element (typically a <button>).',
      avoid: null,
      required: 'aria-controls (pointing to its tabpanel), aria-selected="true|false". Handle arrow key navigation.',
      nestedIn: 'tablist.',
    },
  },
  {
    id: 'tabpanel',
    name: 'tabpanel',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A container for the resources associated with a tab, where each tab is contained in a tablist.',
    usage: {
      element: 'No HTML equivalent. Applied to the content panel associated with a tab.',
      avoid: null,
      required: 'aria-labelledby pointing to the controlling tab. Add tabindex="0" if the panel itself has no focusable children.',
      nestedIn: null,
    },
  },
  {
    id: 'textbox',
    name: 'textbox',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A type of input that allows free-form text as its value.',
    usage: {
      element: 'Implicit on <input type="text"> and <textarea>. Use native inputs wherever possible.',
      avoid: null,
      required: 'Must have an accessible name. Add aria-multiline="true" for multi-line custom textboxes.',
      nestedIn: null,
    },
  },
  {
    id: 'timer',
    name: 'timer',
    primaryCategory: 'widget',
    categories: ['widget', 'live-region'],
    description: 'A numerical counter which indicates an amount of elapsed time from a start point, or the time remaining until an end point.',
    usage: {
      element: 'No HTML equivalent. Applied to a container displaying countdown or elapsed time.',
      avoid: 'Avoid announcing timer changes too frequently — announce only at meaningful intervals to reduce screen reader noise.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'tooltip',
    name: 'tooltip',
    primaryCategory: 'widget',
    categories: ['widget', 'document'],
    description: 'A contextual popup that displays a description for an element.',
    usage: {
      element: 'No HTML equivalent. Applied to the popup container element.',
      avoid: 'Do not put interactive content inside a tooltip. Must not be the only means of conveying important information.',
      required: 'The trigger element must reference the tooltip via aria-describedby.',
      nestedIn: null,
    },
  },
  {
    id: 'treeitem',
    name: 'treeitem',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'An option item of a tree. This is an element within a tree that may be expanded or collapsed if it contains a sub-level group of tree item elements.',
    usage: {
      element: 'No HTML equivalent.',
      avoid: null,
      required: 'aria-expanded="true|false" on expandable items. aria-selected for selectable trees.',
      nestedIn: 'group, which is nested within tree or treeitem.',
    },
  },
  // Composite widget roles
  {
    id: 'grid',
    name: 'grid',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A composite widget containing a collection of one or more rows with one or more cells where some or all cells in the grid are focusable by using methods of two-dimensional navigation, such as directional arrow keys.',
    usage: {
      element: 'No direct HTML equivalent for interactive grids. Use <table> for static tabular data.',
      avoid: null,
      required: 'Must contain row > gridcell structure. Implement 2D keyboard navigation (arrow keys, Home, End, Page Up/Down).',
      nestedIn: null,
    },
  },
  {
    id: 'menu',
    name: 'menu',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A type of widget that offers a list of choices to the user.',
    usage: {
      element: 'No HTML equivalent. Applied to the dropdown container.',
      avoid: 'Do not use for site navigation — use <nav> with links. Menu roles are for application-style action menus.',
      required: 'Trigger button needs aria-haspopup="menu" and aria-expanded. Handle arrow keys and Escape.',
      nestedIn: null,
    },
  },
  {
    id: 'menubar',
    name: 'menubar',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A presentation of menu that usually remains visible and is usually presented horizontally.',
    usage: {
      element: 'No HTML equivalent. Applied to the top-level persistent menu container.',
      avoid: 'Do not use for site navigation. Menubar is for application-style menu systems (File, Edit, View).',
      required: 'Child items should have role="menuitem". Implement horizontal arrow key navigation; vertical for submenus.',
      nestedIn: null,
    },
  },
  {
    id: 'radiogroup',
    name: 'radiogroup',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A group of radio buttons.',
    usage: {
      element: 'Use native <fieldset> + <legend> + <input type="radio"> for standard form groups. radiogroup is for custom implementations.',
      avoid: null,
      required: 'aria-label or aria-labelledby.',
      nestedIn: null,
    },
  },
  {
    id: 'tablist',
    name: 'tablist',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A list of tab elements, which are references to tabpanel elements.',
    usage: {
      element: 'No HTML equivalent. Applied to the container of tab trigger elements.',
      avoid: null,
      required: 'Child items must have role="tab". Implement left/right arrow key navigation between tabs.',
      nestedIn: null,
    },
  },
  {
    id: 'tree',
    name: 'tree',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A widget that allows the user to select one or more items from a hierarchically organized collection.',
    usage: {
      element: 'No HTML equivalent. Applied to the root container of a hierarchical list.',
      avoid: null,
      required: 'Child items: role="treeitem". Nested groups: role="group". Handle arrow keys, Enter, Space, Home, End.',
      nestedIn: null,
    },
  },
  {
    id: 'treegrid',
    name: 'treegrid',
    primaryCategory: 'widget',
    categories: ['widget'],
    description: 'A grid whose rows can be expanded and collapsed in the same manner as for a tree.',
    usage: {
      element: 'No HTML equivalent. Combines tree and grid interaction patterns.',
      avoid: 'Complex to implement accessibly — ensure full keyboard support for both tree expand/collapse and grid 2D navigation.',
      required: 'Row structure: treegrid > row > gridcell. Expandable rows need aria-expanded.',
      nestedIn: null,
    },
  },

  // ── DOCUMENT STRUCTURE ROLES ──────────────────────────────────
  {
    id: 'application',
    name: 'application',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A structure containing one or more focusable elements requiring keyboard interaction, where the normal browser keyboard interaction is to be overridden by the author.',
    usage: {
      element: 'No HTML equivalent.',
      avoid: 'Use with extreme caution. Overrides browser reading mode — AT treats all content as interactive and disables virtual cursor. Almost never needed.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'article',
    name: 'article',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A section of a page that consists of a composition that forms an independent part of a document, page, or site.',
    usage: {
      element: 'Implicit on <article>. Use native <article> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'blockquote',
    name: 'blockquote',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A section of content that is quoted from another source.',
    usage: {
      element: 'Implicit on <blockquote>. Use native <blockquote> — no need to apply this role explicitly.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'caption',
    name: 'caption',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'Visible content that names, and may also describe, a figure, table, grid, or treegrid.',
    usage: {
      element: 'Implicit on <caption> within table, and <figcaption> within figure.',
      avoid: null,
      required: null,
      nestedIn: 'table, grid, treegrid, or figure.',
    },
  },
  {
    id: 'cell',
    name: 'cell',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A cell in a tabular container. See related gridcell.',
    usage: {
      element: 'Implicit on <td> within a table. Use native table elements.',
      avoid: null,
      required: null,
      nestedIn: 'row.',
    },
  },
  {
    id: 'columnheader',
    name: 'columnheader',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A cell containing header information for a column.',
    usage: {
      element: 'Implicit on <th scope="col">. Use native <th scope="col"> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: 'row.',
    },
  },
  {
    id: 'definition',
    name: 'definition',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A definition of a term or concept. See related term.',
    usage: {
      element: 'Implicit on <dd> within <dl>. Use native <dl>/<dd> structure wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'deletion',
    name: 'deletion',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'Content that represents a deletion from a document.',
    usage: {
      element: 'Implicit on <del>. Use native <del> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'directory',
    name: 'directory',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A list of references to members of a group, such as a static table of contents.',
    usage: {
      element: 'No direct HTML equivalent.',
      avoid: 'Deprecated in ARIA 1.2. Use role="list" with appropriate navigation context instead.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'document',
    name: 'document',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'An element containing content that assistive technology users may want to browse in a reading mode.',
    usage: {
      element: 'Implicit on <body> in most contexts. Apply within a role="application" region to restore reading mode for embedded content.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'emphasis',
    name: 'emphasis',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'One or more words that have been emphasized.',
    usage: {
      element: 'Implicit on <em>. Use native <em> — do not apply this role explicitly.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'feed',
    name: 'feed',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A scrollable list of articles where scrolling may cause articles to be added to or removed from either end of the list.',
    usage: {
      element: 'No HTML equivalent. Applied to the scroll container of a dynamically loading article list.',
      avoid: null,
      required: 'aria-label or aria-labelledby. Child articles should have role="article" with aria-posinset and aria-setsize.',
      nestedIn: null,
    },
  },
  {
    id: 'figure',
    name: 'figure',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A perceivable section of content that typically contains a graphical document, images, code snippets, or example text.',
    usage: {
      element: 'Implicit on <figure>. Use native <figure> with <figcaption> for the accessible name.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'group',
    name: 'group',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A set of user interface objects that is not intended to be included in a page summary or table of contents by navigating or assisting technology.',
    usage: {
      element: 'No single HTML equivalent. Often maps to <fieldset> or a wrapping <div>.',
      avoid: 'Does not create a landmark — content will not appear in landmark navigation summaries.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'heading',
    name: 'heading',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A heading for a section of the page.',
    usage: {
      element: 'Implicit on <h1>–<h6>. Use native heading elements wherever possible.',
      avoid: null,
      required: 'aria-level="1–6" when applied to non-heading elements.',
      nestedIn: null,
    },
  },
  {
    id: 'img',
    name: 'img',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A container for a collection of elements that form an image.',
    usage: {
      element: 'Implicit on <img>. Also used on <svg> or composite elements representing a single image.',
      avoid: null,
      required: 'Must have an accessible name via aria-label or aria-labelledby. Use aria-hidden="true" for decorative images.',
      nestedIn: null,
    },
  },
  {
    id: 'insertion',
    name: 'insertion',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'Content that represents an addition to a document.',
    usage: {
      element: 'Implicit on <ins>. Use native <ins> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'list',
    name: 'list',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A section containing listitem elements.',
    usage: {
      element: 'Implicit on <ul> and <ol>. Re-apply role="list" if CSS (list-style: none) has removed implicit list semantics in Safari.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'listitem',
    name: 'listitem',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A single item in a list or directory.',
    usage: {
      element: 'Implicit on <li> within <ul> or <ol>.',
      avoid: null,
      required: null,
      nestedIn: 'list or directory.',
    },
  },
  {
    id: 'math',
    name: 'math',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'Content that represents a mathematical expression.',
    usage: {
      element: 'Implicit on <math> (MathML).',
      avoid: null,
      required: 'Provide a text alternative for the expression via aria-label or adjacent visible text.',
      nestedIn: null,
    },
  },
  {
    id: 'none',
    name: 'none',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'An element whose implicit native role semantics will not be mapped to the accessibility API. See synonym presentation.',
    usage: {
      element: 'Applied to any element to remove its native role. Common uses: <li role="none"> in nav menus, <table role="none"> for layout tables.',
      avoid: 'Do not apply to focusable elements — role is ignored when the element receives focus.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'note',
    name: 'note',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A section whose content is parenthetic or ancillary to the main content of the resource.',
    usage: {
      element: 'No HTML equivalent. Apply to a container for supplementary notes or tips that do not warrant a full aside landmark.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'paragraph',
    name: 'paragraph',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A paragraph of content.',
    usage: {
      element: 'Implicit on <p>. Use native <p> — no need to apply this role explicitly.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'presentation',
    name: 'presentation',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'An element whose implicit native role semantics will not be mapped to the accessibility API. See synonym none.',
    usage: {
      element: 'Synonym for none. Commonly used on <li> in nav menus and <table> rows in layout contexts.',
      avoid: 'Do not apply to focusable elements — focus causes the role to be ignored.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'row',
    name: 'row',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A row of cells in a tabular container.',
    usage: {
      element: 'Implicit on <tr>. Use native table elements wherever possible.',
      avoid: null,
      required: null,
      nestedIn: 'rowgroup, grid, treegrid, or table.',
    },
  },
  {
    id: 'rowgroup',
    name: 'rowgroup',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A structure containing one or more row elements in a tabular container.',
    usage: {
      element: 'Implicit on <thead>, <tbody>, and <tfoot>. Use native table elements.',
      avoid: null,
      required: null,
      nestedIn: 'table or grid.',
    },
  },
  {
    id: 'rowheader',
    name: 'rowheader',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A cell containing header information for a row in a grid.',
    usage: {
      element: 'Implicit on <th scope="row">. Use native <th scope="row"> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: 'row.',
    },
  },
  {
    id: 'separator',
    name: 'separator',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A divider that separates and distinguishes sections of content or groups of menuitems.',
    usage: {
      element: 'Implicit on <hr> as a static (non-focusable) separator.',
      avoid: null,
      required: 'When focusable (widget form): aria-orientation, aria-valuenow, aria-valuemin, aria-valuemax.',
      nestedIn: null,
    },
  },
  {
    id: 'strong',
    name: 'strong',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'Content that is important, serious, or urgent.',
    usage: {
      element: 'Implicit on <strong>. Use native <strong> — no need to apply this role explicitly.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'subscript',
    name: 'subscript',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'One or more subscripted characters.',
    usage: {
      element: 'Implicit on <sub>. Use native <sub> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'superscript',
    name: 'superscript',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'One or more superscripted characters.',
    usage: {
      element: 'Implicit on <sup>. Use native <sup> wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'table',
    name: 'table',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A section containing data arranged in rows and columns, similar to the HTML table element.',
    usage: {
      element: 'Implicit on <table>. Use native <table> for tabular data.',
      avoid: 'Do not use tables for layout — use CSS Grid or Flexbox.',
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'term',
    name: 'term',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A word or phrase with an optional corresponding definition. See related definition.',
    usage: {
      element: 'Implicit on <dt> within <dl> and on <dfn>. Use native elements wherever possible.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'time',
    name: 'time',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'An element that represents a specific period in time.',
    usage: {
      element: 'Implicit on <time>. Use native <time> with a datetime attribute.',
      avoid: null,
      required: null,
      nestedIn: null,
    },
  },
  {
    id: 'toolbar',
    name: 'toolbar',
    primaryCategory: 'document',
    categories: ['document'],
    description: 'A collection of commonly used function buttons or controls represented in a compact visual form.',
    usage: {
      element: 'No HTML equivalent. Applied to the container of grouped action controls.',
      avoid: null,
      required: 'aria-label or aria-labelledby. Implement arrow key navigation between toolbar items.',
      nestedIn: null,
    },
  },

  // ── WINDOW ROLES ──────────────────────────────────────────────
  {
    id: 'alertdialog',
    name: 'alertdialog',
    primaryCategory: 'window',
    categories: ['widget', 'window'],
    description: 'A type of dialog that contains an alert message, where initial focus goes to an element within the dialog. See related alert and dialog.',
    usage: {
      element: 'No HTML equivalent. Applied to the dialog container element.',
      avoid: null,
      required: 'aria-labelledby (dialog title) and aria-describedby (the alert message). Must trap focus; Escape closes.',
      nestedIn: null,
    },
  },
  {
    id: 'dialog',
    name: 'dialog',
    primaryCategory: 'window',
    categories: ['widget', 'window'],
    description: 'A dialog is a descendant window of the primary window of a web application. It is used when the application requires information from the user or to give information to the user. Authors SHOULD ensure that all dialogs are labeled and that the user\'s workflow is not interrupted. User agents or assistive technologies MAY provide special means to set the focus to child elements of dialogs.',
    usage: {
      element: 'Implicit on <dialog>. Use native <dialog> in modern browsers.',
      avoid: null,
      required: 'aria-labelledby pointing to the dialog heading. Must trap focus and return it to the trigger on close. Escape closes.',
      nestedIn: null,
    },
  },
]
